name: Release
on:
  workflow_dispatch:
  create:
    tags:
      - v*

jobs:
    deploy:
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v2

        - name: Build, Push and Deploy to Heroku
          id: heroku
          uses: jctaveras/heroku-deploy@v1.0.0
          with:
            email: ${{ secrets.HEROKU_EMAIL }}
            api_key: ${{ secrets.HEROKU_API_KEY }}
            app_name: elu-dinopolis
            dockerfile_path: ''
