name: Release
on:
  create:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install docker, build image and push to docker repository
        uses: docker/build-push-action@v2.2.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: swackles/dinopolis
          tags: latest
          tag_with_sha: true
  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    
    steps:
      - name: Log
        run: echo Deploy
